import os
import subprocess
from pathlib import Path

from cookiecutter import __version__ as cookiecutter_version

if "{{ cookiecutter.use_argparse }}".lower() != "y":
    os.remove(Path("{{ cookiecutter.project_slug }}", "__main__.py"))

generated_message = (
    f"Generated by Cookiecutter {cookiecutter_version}, "
    f"using template: {{ cookiecutter._template }}"
)

with open("README.md", "a") as readme:
    readme.write(f"*{generated_message}*")


if "{{ cookiecutter.init_git }}".lower() == "y":
    subprocess.call(["git", "init"])
    subprocess.call(["git", "add", "."])
    subprocess.call(
        [
            "git",
            "commit",
            "-am",
            generated_message,
        ]
    )
